name: build_cli_annotations
version: 2.1.1-dev
description: >-
  Contains annotations for `package:build_cli`.
  See that package for more information.

homepage: https://github.com/kevmoo/build_cli

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  # Limit version range on args â€“ it's exported
  args: '>=2.0.0 <3.0.0'
  lints: ^2.0.0
  meta: ^1.7.0
