name: build_cli_annotations
version: 1.2.0
description: >-
  Contains annotations for `package:build_cli`.
  See that package for more information.

homepage: https://github.com/kevmoo/build_cli

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  # Limit version range on args â€“ it's exported
  args: '>=1.5.0 <1.7.0'
